project:
  type: website
  output-dir: docs

website:
  title: "lk01sg"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Publications
        href: publications.qmd
      - text: Projects
        href: /projects/
      - text: Media
        href: media.qmd
      - text: Blog
        href: /blog/
    right:
      - text: "GitHub"
        href: https://github.com/lk01sg
      - text: "Scholar"
        href: https://scholar.google.com/citations?user=YOUR_ID
      - text: "ORCID"
        href: https://orcid.org/YOUR-ORCID
      - text: "Mastodon"
        href: https://genomic.social/@lk01sg
  page-footer: "Â© 2025 lk01sg"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
